### ISSUE TITLE
QCMediaPlayer mediaplayer NOT present error while playing video material

### ISSUE THREAD

**Issue by flankechen** [Rajawali/Rajawali#1480]
Thanks a lot for the great work.
I am trying to render videos on a plane. However, video material example on Rajawali example shows up no video (but I had heard the sound) with error log like:

![device-2015-04-20-115307](https://cloud.githubusercontent.com/assets/4598153/7223493/0d8e59e2-e755-11e4-8259-61d736956fb7.png)

04-20 11:36:47.763: E/MediaPlayer-JNI(19295): QCMediaPlayer mediaplayer NOT present
04-20 11:36:47.763: E/MediaPlayer(19295): wzx:setDataSource--filename = /data/app/com.monyetmabuk.rajawali.tutorials-2.apk from fd
04-20 11:36:47.903: E/MediaPlayer(19295): Should have subtitle controller already set 

and crash when press back button with log like: 
W/MediaPlayer(19295): mediaplayer went away with unhandled events
04-20 11:36:57.293: D/Rajawali(19295): Open GL ES Version String: OpenGL ES 3.0 V@66.0 AU@04.04.02.006.090 (CL@)
04-20 11:36:57.313: W/dalvikvm(19295): threadid=12: thread exiting with uncaught exception (group=0x41598d58)
04-20 11:36:57.323: E/AndroidRuntime(19295): FATAL EXCEPTION: GLThread 2836
04-20 11:36:57.323: E/AndroidRuntime(19295): Process: com.monyetmabuk.rajawali.tutorials, PID: 19295
04-20 11:36:57.323: E/AndroidRuntime(19295): java.lang.IllegalStateException
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at android.media.MediaPlayer._setVideoSurface(Native Method)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at android.media.MediaPlayer.setSurface(MediaPlayer.java:715)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at rajawali.materials.textures.VideoTexture.add(VideoTexture.java:72)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at rajawali.materials.textures.TextureManager.taskAdd(TextureManager.java:116)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at rajawali.materials.textures.TextureManager.taskReload(TextureManager.java:225)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at rajawali.renderer.RajawaliRenderer.onSurfaceChanged(RajawaliRenderer.java:440)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
04-20 11:36:57.323: E/AndroidRuntime(19295): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

I am using Rajawali master branch.
it happens to be the same on device with android 4.4.2 and android 5.0.

Any ideas about this?

**Comment by ToxicBakery** [comment]
Which device is this and more specifically do you know which GPU it has?

**Comment by flankechen** [comment]
@ToxicBakery 
I have try it on three device:
1. Qualcomm Snapdragon 800, Adreno 330, android 4.4.2
2. Qualcomm Snapdragon 801, Adreno 330, android 5.0.2
3. MTK, Mali-T760, android 5.0

no one works.

**Comment by jwoolston** [comment]
What commit are you using? It is definitely far from the latest master as the examples have not had that android model for a while.

**Comment by flankechen** [comment]
@jwoolston 
yeap, I track down and find rev 306 got this android model. 
I am not catching up with Rajawali Master and Rajawali Example master cause I am developing with RajawaliVR, depends on commits around 7 month ago

**Comment by jwoolston** [comment]
There is no such thing as rev 306. What is the SHA1 of your commit?

**Comment by flankechen** [comment]
@jwoolston 
years ago I download the zip file in 2014.10.30, rev 306. 
I trace down and find that android toy(
gzi = new GZIPInputStream(mContext.getResources().openRawResource(R.raw.android));)
exists until rev 345 to rev 346. to Object3D android = new Cube(2.0f);

I guess I should update Rajawali and Rajawali Example to find what's going on. 
But I am not sure which is the last rev supporting Rajawali VR

**Comment by jwoolston** [comment]
Are you accessing the git repo via SVN? This is what I mean by there is no such thing as rev 306. GIT uses SHA1 hashes, not revision numbers. As for a revision to update to, 4a988b3b78b9a68f5af58368731a158912c58b56 is the last one I can say for sure.

**Comment by flankechen** [comment]
@jwoolston thanks for the point.  After suffering trial of android studio and github. I can run Rajawali example project (016b2546e00ec193ee93b9f331342aa4f900fa0c)  now!
which just set dependencies for 
project.ext.set('depRajawali', 'org.rajawali3d:rajawali:1.0.232-SNAPSHOT@aar')

however, I got the same error message and views as before. no video shows, but a rendering cube.
![device-2015-05-05-145016](https://cloud.githubusercontent.com/assets/4598153/7468137/4451ae50-f337-11e4-9718-28a3d4258dc9.png)
