### ISSUE TITLE
ShadowEffect have no effect 

### ISSUE THREAD

**Issue by fulean** [Rajawali/Rajawali#1538]
I use the latest master branch of Rajawali, and found ShadowEffect has no effect on android 4.4,

does the dynamic cast shadow feature has yet to implement ?

**Comment by fulean** [comment]
the test rountine is based on the DirectionLightFragment demo, create a plane under the balls plane , then add ShadowEffect and mPostProcessingManager , if ShadowEffect works well , the created plane should received casted shadow of the ball , but nothing appear .this is the test code:


public class DirectionalLightFragment extends AExampleFragment {

	@Override
    public AExampleRenderer createRenderer() {
		return new DirectionalLightRenderer(getActivity());
	}

	private final class DirectionalLightRenderer extends AExampleRenderer {

		private PostProcessingManager mPostProcessingManager = null;
		Material planeMaterial = null ,planeMaterial2 = null;
		public DirectionalLightRenderer(Context context) {
			super(context);
		}

        @Override
		protected void initScene() {
			final DirectionalLight directionalLight = new DirectionalLight();
            directionalLight.setPosition(2.0,1.5,0.1);//(1.0, 0.0, 0.0);
			directionalLight.setPower(2.0f); 	//1.5
            directionalLight.setLookAt(Vector3.ZERO);
            directionalLight.enableLookAt();
			getCurrentScene().addLight(directionalLight);

            getCurrentCamera().enableLookAt();
            getCurrentCamera().setPosition(-1, 2, 6); //026
            getCurrentCamera().setLookAt(0, 0, 0);

			Material sphereMaterial = new Material();
			SpecularMethod.Phong phongMethod = new SpecularMethod.Phong();
			phongMethod.setShininess(180);
			sphereMaterial.setDiffuseMethod(new DiffuseMethod.Lambert());
			sphereMaterial.setSpecularMethod(phongMethod);
			sphereMaterial.enableLighting(true);

			Sphere rootSphere = new Sphere(.2f, 12, 12);
			rootSphere.setMaterial(sphereMaterial);
			rootSphere.setRenderChildrenAsBatch(true);
			rootSphere.setVisible(false);
			getCurrentScene().addChild(rootSphere);

			// -- inner ring

			float radius = .8f;
			int count = 0;

			for (int i = 0; i < 360; i += 36) {
				double radians = MathUtil.degreesToRadians(i);
				int color = 0xfed14f;
				if (count % 3 == 0)
					color = 0x10a962;
				else if (count % 3 == 1)
					color = 0x4184fa;
				count++;

				Object3D sphere = rootSphere.clone(false);
				sphere.setPosition((float) Math.sin(radians) * radius, 0,
						(float) Math.cos(radians) * radius);
				sphere.setMaterial(sphereMaterial);
				sphere.setColor(color);
				rootSphere.addChild(sphere);
			}

			// -- outer ring

			radius = 2.4f;
			count = 0;

			for (int i = 0; i < 360; i += 12) {
				double radians = MathUtil.degreesToRadians(i);
				int color = 0xfed14f;
				if (count % 3 == 0)
					color = 0x10a962;
				else if (count % 3 == 1)
					color = 0x4184fa;
				count++;

				Object3D sphere = rootSphere.clone(false);
				sphere.setPosition((float) Math.sin(radians) * radius, 0,
						(float) Math.cos(radians) * radius);
				sphere.setMaterial(sphereMaterial);
				sphere.setColor(color);
				rootSphere.addChild(sphere);
			}

			EllipticalOrbitAnimation3D anim = new EllipticalOrbitAnimation3D(
					new Vector3(0, 0f, 0), new Vector3(1, 0, 1), 0, 359);
			anim.setRepeatMode(Animation.RepeatMode.INFINITE);
			anim.setDurationMilliseconds(6000);
			anim.setTransformable3D(directionalLight);
			getCurrentScene().registerAnimation(anim);
			//anim.play(); 
			
			//fla++

			planeMaterial =new Material(); //new ShadowMapMaterial(getCurrentCamera(),getCurrentScene(),directionalLight);//
			planeMaterial.setDiffuseMethod(new DiffuseMethod.Lambert());
			//planeMaterial.setSpecularMethod(phongMethod);
			planeMaterial.enableLighting(true);
		
			Plane plane = new Plane(Vector3.Axis.Y); 
			plane.setScale(100);
			plane.setMaterial(planeMaterial);
			plane.setColor(Color.WHITE); 
			plane.setY(-.4f);
			getCurrentScene().addChild(plane);

			getCurrentScene().setBackgroundColor(0.7f, 0.7f, 0.7f, 1.0f);
			

			mPostProcessingManager = new PostProcessingManager(this);
		        ShadowEffect shadowEffect = new ShadowEffect(getCurrentScene(), getCurrentCamera(), directionalLight, 2048);
			shadowEffect.setShadowInfluence(.8f);	//.5f
			mPostProcessingManager.addEffect(shadowEffect); 
			shadowEffect.setRenderToScreen(true);
		}

		@Override
        public void onRender(final long ellapsedTime, final double deltaTime) {
			mPostProcessingManager.render(ellapsedTime, deltaTime);
		}
		
		
				

	}

}

**Comment by MasDennis** [comment]
Unfortunately the shadows don't work anymore. It broke after the big quaternion rewrite. Fixing this has priority but I'm afraid all of the team members have other commitments outside of Rajawali. I don't expect anyone will be able to fix it anytime soon. You could try reverting back to old revisions. Your best bet would be to get a version from >= 2 juli 2014

**Comment by fulean** [comment]
thanks, reverting  to which old version can support shadow casting normally ?

**Comment by fulean** [comment]
after reset to 2 july 2014, shadowmap works , hope your team will add shadow map to new version soon  it's a very useful and powerful engine.

**Comment by fulean** [comment]
i found a problem that,when use shadowmap, material can't addtexture,otherwise rajawali will crash,

report an fatal errors as below:

08-08 23:29:52.546: E/AndroidRuntime(13564): FATAL EXCEPTION: GLThread 1976
08-08 23:29:52.546: E/AndroidRuntime(13564): Process: com.monyetmabuk.rajawali.tutorials, PID: 13564
08-08 23:29:52.546: E/AndroidRuntime(13564): java.lang.RuntimeException: OpenGL Error: invalid operation 1282
08-08 23:29:52.546: E/AndroidRuntime(13564): 	at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:387)
08-08 23:29:52.546: E/AndroidRuntime(13564): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
08-08 23:29:52.546: E/AndroidRuntime(13564): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by fulean** [comment]
@MasDennis 

I fixed the shadowmap crash which caused by add a texture to the material. but the casted shadow on the object with a material that contains one or more  texture will distortion.

have you tried shadowEffect on material with texture ?

**Comment by jwoolston** [comment]
I am moving this (and other shadow related issues) to a new issue for consolidation and closing this one. The references will be made however.

**Comment by wangcan26** [comment]
Have this bug fixed? @jwoolston @MasDennis

**Comment by jwoolston** [comment]
Not yet.
