### ISSUE TITLE
Potential renderer contribution + request for help for out of memory error

### ISSUE THREAD

**Issue by adamantivm** [Rajawali/Rajawali#1543]
For one of our apps we built a sort of "picture in picture" Rajawali renderer. It allows to attach two separate renderers and render them in the same RajawaliView. This was as a result of advice provided [in this other issue](https://github.com/Rajawali/Rajawali/issues/1518).

We are in the process of cleaning up this code and preparing a PR, which [you can see here](https://github.com/Rajawali/Rajawali/compare/master...creativa77:pip-renderer)

But there is still one remaining issue which is also haunting our app and we can't figure out: if the application is paused and resumed, it crashes with an out of memory error:

```
08-19 11:50:53.111  16408-16426/? E/Rajawali﹕ Could not create framebuffer: [1285]: out of memory
08-19 11:50:53.175  16408-16426/? E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 922
    Process: com.ekumen.rajawaliexamplepip, PID: 16408
    java.lang.RuntimeException: Could not create framebuffer: [1285]: out of memory
            at org.rajawali3d.renderer.RenderTarget.checkGLError(RenderTarget.java:321)
            at org.rajawali3d.renderer.RenderTarget.create(RenderTarget.java:241)
            at org.rajawali3d.renderer.RenderTarget.reload(RenderTarget.java:312)
            at org.rajawali3d.renderer.RajawaliRenderer.reloadRenderTargets(RajawaliRenderer.java:985)
            at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:365)
            at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onSurfaceChanged(RajawaliSurfaceView.java:223)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1512)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-19 11:50:53.179     994-7881/? W/ActivityManager﹕ Force finishing activity com.ekumen.rajawaliexamplepip/.MainActivity
```

The code that produces this is split into a [very simple sample application](https://github.com/creativa77/RajawaliExamplePip/tree/master/app/src/main/java/com/ekumen/rajawaliexamplepip) and [the renderer subclass](https://github.com/Rajawali/Rajawali/compare/master...creativa77:pip-renderer). The full logcat after application resume [is in this gist](https://gist.github.com/adamantivm/5a41e7df80b76c9dfde5)

I would greatly appreciate your help figuring out where this problem is coming from.

**Comment by adamantivm** [comment]
Ahhhhh.
After arduous and tenacious debugging I found that the issue was on my intended contribution (the RajawaliPipRenderer). In partiucular, I was creating a new RajawaliScene for each sub-scene but was neglecting to do a corresponding addScene() for each of these new scenes, and that was causing the above mentioned exception.

Now I can solve my issue and subsequently, after some clean-up, pull request this contribution which hopefully people may find handy.
