### ISSUE TITLE
Matrix4 error on importing md5 object

### ISSUE THREAD

**Issue by Dumi1986** [Rajawali/Rajawali#1571]
I am trying to import an md5 skeletal animation with texture, but errors appears in logcat. I mention that the md5 3D object is exported from blender v2.76, with id tech 4 MD5 plugin.  Below is the code from Renderer class.

public class Renderer extends RajawaliRenderer {

        private static final String TAG = "Test";
        

    public void initScene() {
     
        getCurrentCamera().setPosition(0, 0, 10);
        getCurrentCamera().setLookAt(0, 0, 0);

      try {

            ScreenQuad quad = new ScreenQuad(true);
            quad.rotateAround(Vector3.Z, 180f);
            Material material = new Material();
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.addTexture(new Texture("rajawaliTex", R.drawable.dota2_dire));
            Log.d("Rajawali", "Number of textures loaded: " + mTextureManager.getNumTextures());
            material.setColorInfluence(0);
            quad.setMaterial(material);
            getCurrentScene().addChild(quad);
            Log.i(TAG, "Background");

          // -- Load the .md5mesh file from the raw resource folder
          LoaderMD5Mesh meshParser = new LoaderMD5Mesh(this, R.raw.boblampcleanmesh);
          meshParser.parse();
          Log.i(TAG, "Load mesh");

         // -- Load the .md5anim file from the raw resource folder
         LoaderMD5Anim animParser = new LoaderMD5Anim("animation1", this, R.raw.boblampcleananim);
          animParser.parse();
          Log.i(TAG, "Load anim");  

          // -- Get the animation sequence
          SkeletalAnimationSequence sequence = (SkeletalAnimationSequence)animParser.getParsedAnimationSequence();
          Log.i(TAG, "Get the animation sequence");

           // -- Get the parsed AnimationSkeleton object
          SkeletalAnimationObject3D animationAxe = (SkeletalAnimationObject3D)meshParser.getParsedAnimationObject();
          Log.i(TAG, " Get the parsed AnimationSkeleton object");

          // -- Set the animation. You can use multiple .md5anim files in your project for one
          //    .md5mesh file
          animationAxe.setAnimationSequence(sequence);
          Log.i(TAG, "Set the animation");
          animationAxe.setScale(.04f);
          animationAxe.setRotY(180);

          Material axeMaterial = new Material();
          animationAxe.setMaterial(axeMaterial);
          getCurrentScene().addChild(animationAxe);

          // -- Play the animation
          // animationAxe.play();
          Log.i(TAG, "Play the animation");          

        } catch (ATexture.TextureException e) {
            e.printStackTrace();
        } catch (ParsingException e) {
            e.printStackTrace();
        }
    }

    public void onSurfaceCreated(GL10 gl, EGLConfig config) {
        super.onSurfaceCreated(gl, config);
    }

    public void onDrawFrame(GL10 glUnused) {
        super.onDrawFrame(glUnused);
    }
}

Here it is the logcat response.

01-02 13:52:09.437 3354-3368/? D/Rajawali: Open GL ES Version String: OpenGL ES 2.0 (3.1.0 - Build 9.17.10.3347)
01-02 13:52:09.437 3354-3368/? D/Rajawali: Derived GL ES Version: 2.0
01-02 13:52:09.438 3354-3368/? D/Renderer: onSurfaceChanged()
01-02 13:52:09.480 3354-3368/? D/Rajawali: Number of textures loaded: 0
01-02 13:52:09.480 3354-3368/? I/Test: Background
01-02 13:52:09.481 3354-3368/? D/Rajawali: MD5 Version: 10
01-02 13:52:09.642 3354-3368/? I/Test: Load mesh
01-02 13:52:09.820 3354-3368/? I/Test: Load anim
01-02 13:52:09.820 3354-3368/? I/Test: Get the animation sequence
01-02 13:52:09.820 3354-3368/? I/Test:  Get the parsed AnimationSkeleton object
01-02 13:52:09.820 3354-3368/? I/Test: Set the animation
01-02 13:52:09.820 3354-3368/? I/Test: Play the animation
01-02 13:52:10.067 3354-3368/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab7d13f0
01-02 13:52:10.070 3354-3368/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 172
                                                 Process: ro.livewallpaper.dota2, PID: 3354
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'double[] org.rajawali3d.math.Matrix4.getDoubleValues()' on a null object reference
                                                     at org.rajawali3d.math.Matrix4.leftMultiply(Matrix4.java:390)
                                                     at org.rajawali3d.animation.mesh.SkeletalAnimationChildObject3D.calculateModelMatrix(SkeletalAnimationChildObject3D.java:92)
                                                     at org.rajawali3d.ATransformable3D.onRecalculateModelMatrix(ATransformable3D.java:67)
                                                     at org.rajawali3d.Object3D.render(Object3D.java:262)
                                                     at org.rajawali3d.Object3D.render(Object3D.java:371)
                                                     at org.rajawali3d.Object3D.render(Object3D.java:240)
                                                     at org.rajawali3d.animation.mesh.SkeletalAnimationObject3D.render(SkeletalAnimationObject3D.java:270)
                                                     at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:844)
                                                     at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:719)
                                                     at org.rajawali3d.renderer.RajawaliRenderer.render(RajawaliRenderer.java:529)
                                                     at org.rajawali3d.renderer.RajawaliRenderer.onRender(RajawaliRenderer.java:519)
                                                     at org.rajawali3d.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:488)
                                                     at ro.livewallpaper.dota2.Renderer.onDrawFrame(Renderer.java:176)
                                                     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by Dumi1986** [comment]
I am still waiting for a hint :)

**Comment by ToxicBakery** [comment]
Looks like the model failed to parse properly or is corrupt. Most likely the parser did not quite understand the format. Quality PR's are welcome.
