### ISSUE TITLE
Opening obj file located in internal phone memory

### ISSUE THREAD

**Issue by Ornolfr** [Rajawali/Rajawali#1575]
How can I use LoaderOBJ or what class should I use to parse an .obj file located in the phone memory? Why has MeshExporter class become deprecated? Where is ExportType class?

**Comment by jwoolston** [comment]
Exporting, serialization and the like have been abandoned in favor of using the AWD format. The workflow is simpler because it can be done on the PC rather than on the device and frankly, the AWD importer is more reliable then ours as they have more resources to handle the large variation the OBJ file format allows for. As for how to use `LoaderOBJ`, see this example: https://github.com/Rajawali/RajawaliExamples/blob/master/examples/src/main/java/com/monyetmabuk/rajawali/tutorials/examples/loaders/LoadModelFragment.java

**Comment by Ornolfr** [comment]
Ok, I actually figured out how to open obj files from phone memory, it works fine, though with some errors in the log:
```
02-22 12:05:16.769 21394-21394/com.vi3dim.recon_3d E/Rajawali: [org.rajawali3d.loader.LoaderOBJ.MaterialLib] Could not find file.
02-22 12:05:16.770 21394-21394/com.vi3dim.recon_3d W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.vi3dim.recon_3d/files/00058_mts_mesh1_obj_mtl: open failed: ENOENT (No such file or directory)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at java.io.FileReader.<init>(FileReader.java:42)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at org.rajawali3d.loader.LoaderOBJ$MaterialLib.parse(LoaderOBJ.java:502)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at org.rajawali3d.loader.LoaderOBJ.parse(LoaderOBJ.java:271)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at com.vi3dim.recon_3d.scan.viewer.Renderer.loadScene(Renderer.java:88)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at com.vi3dim.recon_3d.scan.viewer.ViewerFragment.onActivityResult(ViewerFragment.java:113)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6139)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3581)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3628)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:151)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-22 12:05:16.772 21394-21394/com.vi3dim.recon_3d W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5281)
02-22 12:05:16.773 21394-21394/com.vi3dim.recon_3d W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-22 12:05:16.773 21394-21394/com.vi3dim.recon_3d W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-22 12:05:16.773 21394-21394/com.vi3dim.recon_3d W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
02-22 12:05:16.773 21394-21394/com.vi3dim.recon_3d W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
02-22 12:05:16.773 21394-21394/com.vi3dim.recon_3d W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
02-22 12:05:16.774 21394-21394/com.vi3dim.recon_3d W/System.err:     at libcore.io.Posix.open(Native Method)
02-22 12:05:16.774 21394-21394/com.vi3dim.recon_3d W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
02-22 12:05:16.774 21394-21394/com.vi3dim.recon_3d W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
02-22 12:05:16.774 21394-21394/com.vi3dim.recon_3d W/System.err: 	... 18 more
```
What's the deal with this?

**Comment by ToxicBakery** [comment]
`FileNotFoundException: /storage/emulated/0/Android/data/com.vi3dim.recon_3d/files/00058_mts_mesh1_obj_mtl`

You are missing data that should come with the obj.

**Comment by jwoolston** [comment]
Closing this issue as stale. Please add additional info if this is still a problem.
