### ISSUE TITLE
VR module giving null object reference

### ISSUE THREAD

**Issue by kmare** [Rajawali/Rajawali#1620]
#### Rajawali Version or Branch
Rajawali-1.1.0-SNAPSHOT (from 18-3-2016)

#### Device and Android Version (Please include the complete model number not just 'Galaxy S6', especially if its a Samsung)
Google Nexus5 on Android 6.0.1

#### Summary
Exiting a very simple app consisting of just a plane, the below exception is thrown. If you need anything else, I'll gladly provide it. Thank you!

#### Steps to Reproduce (Sample code is helpful)
Simply press the back button.

#### Trace or Log Output
java.lang.NullPointerException: Attempt to read from field 'org.rajawali3d.renderer.ISurfaceRenderer org.rajawali3d.vr.surface.VRSurfaceView$RendererDelegate.mRenderer' on a null object reference
                                                                               at org.rajawali3d.vr.surface.VRSurfaceView.onDetachedFromWindow(VRSurfaceView.java:146)
                                                                               at android.view.View.dispatchDetachedFromWindow(View.java:14561)
                                                                               at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)

**Comment by jwoolston** [comment]
Yes I have seen this as well.

**Comment by jwoolston** [comment]
There appears to be a threading with this, a simple null check is not sufficient.

**Comment by kmare** [comment]
The fix worked fine for me, thank you!
