### ISSUE TITLE
NullPointerException on surfaceCreated() on VR Module 

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [Rajawali/Rajawali#1635]
#### Rajawali Version or Branch
commit d9d8971 

#### Device and Android Version
Note 5 SM-N920I Android 5.1.1 

#### Summary
Crash on `addContentView(mSurfaceView, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT));`

#### Steps to Reproduce
1- Integrate vr Module 
2- write this code 
````java
mSurfaceView = new VRSurfaceView(this);

addContentView(mSurfaceView, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT));

int uiFlags = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
			| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
			| View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
			| View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
			| View.SYSTEM_UI_FLAG_FULLSCREEN; // hide status bar
if (VERSION.SDK_INT >= VERSION_CODES.KITKAT) {
    uiFlags |= View.SYSTEM_UI_FLAG_IMMERSIVE;
}
mSurfaceView.setSystemUiVisibility(uiFlags);

setCardboardView(mSurfaceView);
````

#### Trace or Log Output
````
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.surfaceCreated()' on a null object reference
                                                                      at android.opengl.GLSurfaceView.surfaceCreated(GLSurfaceView.java:559)
                                                                      at android.view.SurfaceView.updateWindow(SurfaceView.java:688)
                                                                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:200)
                                                                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2301)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7017)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6897)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
````

**Comment by jwoolston** [comment]
The code you posted is verbatim what is in the `VRActivity` class from the Rajawali VR module. Why not simply use it? If you are making your own activity are you inheriting from `CardboardActivity`? This is a requirement for that code to function.

**Comment by mahmoud-elnaggar** [comment]
Yes I'm using it and gave me same exception , and I tried to extend `CardboardActivity` and write this code on my activity

**Comment by jwoolston** [comment]
Does the VR example in the examples application work on this device?

**Comment by mahmoud-elnaggar** [comment]
yes it works, I know it is weird 
but I changed somethings on gradle to integrate it on my app and I don't think they are related to this crash. 
I'll do a small demo and if it still happening ,I'll send you this demo

**Comment by jwoolston** [comment]
Sounds good.

**Comment by mahmoud-elnaggar** [comment]
it fixed , thanks so much
