### ISSUE TITLE
Can't use two or more instances of Rajawali in another fragment

### ISSUE THREAD

**Issue by st-f** [Rajawali/Rajawali#1728]
#### Rajawali Version or Branch
master

#### Device and Android Version
Nexus 5X

#### Summary
Can't use two or more instances of Rajawali in another fragment

#### Steps to Reproduce
A fragment contains a RajawaliRenderer and a RenderSurface.  Loads an OBJ model (the same). Use this fragment side by side (2 instances) in another fragment. The OBJ either disappear or is incorrectly rendered in the first instance, everything is fine in the second instance.

Screenshot [here](http://imgur.com/a/kRajv).

#### Trace or Log Output

Multiple times:

Getting location of uniform: uTime returned -1!
08-15 10:42:17.088 11551-12472/net.stf.timelapser E/Rajawali: Getting location of uniform: uLightPosition0 returned -1!
08-15 10:42:17.088 11551-12472/net.stf.timelapser E/Rajawali: Getting location of uniform: uLightPosition1 returned -1!

Ends with:

FATAL EXCEPTION: RajawaliGLThread 2944
                                                                    Process: net.stf.timelapser, PID: 11551
                                                                    java.lang.IllegalArgumentException: string == null
                                                                        at android.opengl.GLES20.glShaderSource(Native Method)
                                                                        at org.rajawali3d.materials.Material.loadShader(Material.java:731)
                                                                        at org.rajawali3d.materials.Material.createProgram(Material.java:756)
                                                                        at org.rajawali3d.materials.Material.createShaders(Material.java:679)
                                                                        at org.rajawali3d.materials.Material.useProgram(Material.java:789)
                                                                        at org.rajawali3d.Object3D.render(Object3D.java:253)
                                                                        at org.rajawali3d.Object3D.render(Object3D.java:318)
                                                                        at org.rajawali3d.Object3D.render(Object3D.java:318)
                                                                        at org.rajawali3d.Object3D.render(Object3D.java:181)
                                                                        at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:1109)
                                                                        at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:971)
                                                                        at org.rajawali3d.renderer.Renderer.render(Renderer.java:421)
                                                                        at org.rajawali3d.renderer.Renderer.onRender(Renderer.java:411)
                                                                        at org.rajawali3d.renderer.Renderer.onRenderFrame(Renderer.java:386)
                                                                        at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1277)
                                                                        at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:997)

**Comment by st-f** [comment]
I found the issue. The OBJ model had no material attached to it, causing rendering issues despite me setting the material manually once loaded. Blender generates an empty material which is not working with Rajawali. It works using this material from the examples:

newmtl MonkeyMaterial
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.555097 0.193825 0.007777
Ks 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 1
