### ISSUE TITLE
The library libVuforia.so and libRajawaliVuforia.so could not be loaded

### ISSUE THREAD

**Issue by li96968510** [Rajawali/Rajawali#1759]
I only run the Rajawali-master ( examples). and click " Vuforia Integration",
 the class is  VuforiaExampleFragment.

log message:
370 30214-30214/org.rajawali3d.examples E/Rajawali: The library libVuforia.so could not be loaded
09-02 16:50:14.385 30214-30214/org.rajawali3d.examples E/Rajawali: The library libRajawaliVuforia.so could not be loaded
09-02 16:50:14.388 30214-30214/org.rajawali3d.examples E/art: No implementation found for void org.rajawali3d.vuforia.VuforiaManager.setCloudRecoDatabase(java.lang.String, java.lang.String) (tried Java_org_rajawali3d_vuforia_VuforiaManager_setCloudRecoDatabase and Java_org_rajawali3d_vuforia_VuforiaManager_setCloudRecoDatabase__Ljava_lang_String_2Ljava_lang_String_2)
09-02 16:50:14.388 30214-30214/org.rajawali3d.examples D/AndroidRuntime: Shutting down VM
09-02 16:50:14.389 30214-30214/org.rajawali3d.examples E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.rajawali3d.examples, PID: 30214
                                                                         java.lang.UnsatisfiedLinkError: No implementation found for void org.rajawali3d.vuforia.VuforiaManager.setCloudRecoDatabase(java.lang.String, java.lang.String) (tried Java_org_rajawali3d_vuforia_VuforiaManager_setCloudRecoDatabase and Java_org_rajawali3d_vuforia_VuforiaManager_setCloudRecoDatabase__Ljava_lang_String_2Ljava_lang_String_2)
                                                                             at org.rajawali3d.vuforia.VuforiaManager.setCloudRecoDatabase(Native Method)
                                                                             at com.rajawali3d.examples.examples.vr_ar.VuforiaExampleFragment.onCreate(VuforiaExampleFragment.java:61)
                                                                             at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
                                                                             at android.support.v4.app.BackStackRecord.ensureFragmentsAreInitialized(BackStackRecord.java:1077)
                                                                             at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1032)
                                                                             at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:658)
                                                                             at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                             at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                             at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                             at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1241)
                                                                             at android.app.Activity.performStart(Activity.java:6387)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2407)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:150)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by strider2023** [comment]
@li96968510 did you find any fix for this?? Facing the same issue...tried lots of work arounds but in vain. Any help would be greatly appreciated.

**Comment by jwoolston** [comment]
Its broken in the current version and it will stay that way for the time being due to the licensing requirement changes of Vuforia, unless someone decides it matters enough to pay me to fix it now, it will be resolved after I work through v2.0
