### ISSUE TITLE
unexpected behaviour from Geometry3D.addFromGeometry3D

### ISSUE THREAD

**Issue by contriteobserver** [Rajawali/Rajawali#1760]
#### Rajawali Version or Branch
master

#### Device and Android Version
SM-T230N

#### Summary
`NullPointerException` thrown in `Geometry3D.addFromGeometry3D`

#### Steps to Reproduce
Was hoping to use `Geometry3D.addFromGeometry3D` to augment geometry at runtime.

```
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            try {
                Geometry3D geometry;
                Material red = new Material();
                red.setColor(Color.RED);
                Material cyan = new Material();
                cyan.setColor(Color.CYAN);
                Material yellow = new Material();
                yellow.setColor(Color.YELLOW);
                Material magenta = new Material();
                magenta.setColor(Color.MAGENTA);

                float[] vertices = new float[] {
                        -0.5f, 0.5f, 0,
                        -0.5f,-0.5f, 0,
                        0.5f,-0.5f, 0,
                        0.5f, 0.5f, 0,
                };
                float[] normals = null;
                float[] textureCoords = null;
                float[] colors = null;
                int[] indices = new int[] {
                        0,1,2,
                        0,2,3,
                };
                boolean createVBOs = true;

                geometry = new Geometry3D();
                geometry.setData(vertices, normals, textureCoords, colors, indices, createVBOs);
                Object3D obj1 = new Object3D();
                obj1.isContainer(false);
                obj1.getGeometry().setData(vertices, normals, textureCoords, colors, indices, createVBOs);
                obj1.setPosition(-0.5,0.5,0);
                obj1.setMaterial(red);
                getCurrentScene().addChild(obj1);

                geometry = new Geometry3D();
                geometry.setData(vertices, normals, textureCoords, colors, indices, createVBOs);
                Object3D obj2 = new Object3D();
                obj2.isContainer(false);
                obj2.getGeometry().setVertices(vertices);
                obj2.getGeometry().setIndices(indices);
                obj2.getGeometry().createBuffers();
                obj2.setPosition(0.5,0.5,0);
                obj2.setMaterial(cyan);
                getCurrentScene().addChild(obj2);

                geometry = new Geometry3D();
                geometry.setData(vertices, normals, textureCoords, colors, indices, createVBOs);
                Object3D obj3 = new Object3D();
                obj3.isContainer(false);
                obj3.getGeometry().copyFromGeometry3D(geometry);
                obj3.setPosition(-0.5,-0.5,0);
                obj3.setMaterial(yellow);
                getCurrentScene().addChild(obj3);

                geometry = new Geometry3D();
                geometry.setData(vertices, normals, textureCoords, colors, indices, createVBOs);
                Object3D obj4 = new Object3D();
                obj4.isContainer(false);
                obj4.getGeometry().addFromGeometry3D(Vector3.ZERO, geometry, createVBOs);
                obj4.setPosition(0.5,-0.5,0);
                obj4.setMaterial(magenta);
                getCurrentScene().addChild(obj4);

                getCurrentCamera().setLookAt(Vector3.ZERO);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
```
#### Trace or Log Output
```
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err: java.lang.NullPointerException
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at org.rajawali3d.Geometry3D.getFloatArrayFromBuffer(Geometry3D.java:197)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at org.rajawali3d.Geometry3D.addFromGeometry3D(Geometry3D.java:274)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at com.example.localrajawalispike.LocalRajawaliActivity$GeometryRenderer.initScene(LocalRajawaliActivity.java:389)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:345)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:230)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
09-03 11:34:55.416 8420-8448/com.example.localrajawalispike W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by jwoolston** [comment]
Closed via #1761
