### ISSUE TITLE
NPE on swapping between fragments using TextureView

### ISSUE THREAD

**Issue by lschuetze** [Rajawali/Rajawali#1773]
#### Rajawali Version or Branch
version 1.1.610@aar

#### Device and Android Version
Samsung Galaxy Tab S4, Android 6

#### Summary
I have two fragments. When switching between the two fragments the application crashes with a NullPointerException thrown in the `onResume` method of `TextureView`.  Both fragments have a `TextureView`. Even if I set the surfaces renderer in `Fragment.onResume` it will make the application crash.

#### Steps to Reproduce
Initialization: 

    surfaceView = (TextureView) view.findViewById(R.id.surface_view);
    surfaceView.setFrameRate(1.0);
    surfaceView.setRenderMode(ISurface.RENDERMODE_WHEN_DIRTY);

Setting the renderer in a fragment:

    @Override
    public void onResume() {
      super.onResume();
      surfaceView.setSurfaceRenderer(parent.getRenderer());
    }

Creating the renderer:

      renderer = new SmartLoaderRenderer(this);
      LoaderSTL loader = new LoaderSTL(getResources(), renderer.getTextureManager(), R.raw.smart_loader2);
      renderer.loadModel(loader, renderer.getLoaderCallback(), 1);
#### Trace or Log Output
```
java.lang.NullPointerException: Attempt to read from field 'org.rajawali3d.renderer.ISurfaceRenderer org.rajawali3d.view.TextureView$RendererDelegate.mRenderer' 
on a null object reference
at org.rajawali3d.view.TextureView.onResume(TextureView.java:465)
at org.rajawali3d.view.TextureView.onVisibilityChanged(TextureView.java:163)
at android.view.View.dispatchAttachedToWindow(View.java:15860)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3147)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3147)
at android.view.ViewGroup.addViewInner(ViewGroup.java:4695)
at android.view.ViewGroup.addView(ViewGroup.java:4492)
at android.view.ViewGroup.addView(ViewGroup.java:4433)
at android.view.ViewGroup.addView(ViewGroup.java:4406)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:996)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7231)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jwoolston** [comment]
Generally speaking the system was designed to have one renderer per fragment created and destroyed with the fragment view.

**Comment by jwoolston** [comment]
:point_up: I realize this is constraining....the in progress v2.0 removes this restriction.
