### ISSUE TITLE
Error `java.lang.IllegalArgumentException: string == null` in the class `Material.java`

### ISSUE THREAD

**Issue by SandroMachado** [Rajawali/Rajawali#1817]
#### Rajawali Version or Branch
1.1.777

#### Device and Android Version
Samsung, HUAWEI and LG

#### Summary
Sometimes my app produces an `IllegalArgumentException` error.

#### Steps to Reproduce
Unfortunately I don't have **repro steps**. It looks like a random thing.

#### Trace or Log Output
```
Fatal Exception: java.lang.IllegalArgumentException: string == null
       at android.opengl.GLES20.glShaderSource(GLES20.java)
       at org.rajawali3d.materials.Material.loadShader(Material.java:758)
       at org.rajawali3d.materials.Material.createProgram(Material.java:783)
       at org.rajawali3d.materials.Material.createShaders(Material.java:703)
       at org.rajawali3d.materials.Material.reload(Material.java:491)
       at org.rajawali3d.materials.MaterialManager.taskReload(MaterialManager.java:72)
       at org.rajawali3d.renderer.Renderer.initScene(Renderer.java:367)
       at com.sandro.aerial.RendererActivity.onRenderSurfaceSizeChanged(RendererActivity.java:276)
       at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1528)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)
```

**Comment by jwoolston** [comment]
This looks to be a scene caching error. To help me track down the cause, were you using Rajawali's material building system or loading a custom shader of your own?

**Comment by SandroMachado** [comment]
Hi @jwoolston,

I am using `Rajawali's material building system`. In the class where I get the crash, I just play a video like the example available in the project.

**Comment by jwoolston** [comment]
Ok, I'll look into it.

**Comment by SandroMachado** [comment]
@jwoolston thanks.

If I found more information related to the issue, I will add it here.

**Comment by shaji-Dev** [comment]
I still get this error when using two Rajawali SurfaceView in my app. Any fix yet?
Thank you.

**Comment by LyCharlie** [comment]
same error , any update?

**Comment by contriteobserver** [comment]
@LyCharlie are there more than one Rajawali SurfaceView in your app?

**Comment by LyCharlie** [comment]
I use `org.rajawali3d:rajawali:1.1.970@aar` and viewpage2 , it happens when I switch page

**Comment by chiel99** [comment]
Found same crash in my Crashlytics reports:
Ver: 1.1.970
With single Rajawali SurfaceView with bitmap textures

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, what is wrong with this example?

MainActivity.java
```
public class MainActivity extends FragmentActivity {
    private static final int NUM_PAGES = 5;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ViewPager2 viewPager = findViewById(R.id.pager);
        viewPager.setOffscreenPageLimit(NUM_PAGES-1);
        viewPager.setAdapter(new ScreenSlidePagerAdapter(this));
    }

    private class ScreenSlidePagerAdapter extends FragmentStateAdapter {
        ScreenSlidePagerAdapter(FragmentActivity fa) {
            super(fa);
        }

        @NonNull
        @Override
        public Fragment createFragment(int position) {
            return new ScreenSlideGlslFragment();
        }

        @Override
        public int getItemCount() {
            return NUM_PAGES;
        }
    }

}
```

ScreenSlideGlslFragment.java
```
public class ScreenSlideGlslFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        ViewGroup rootView = (ViewGroup) inflater.inflate(
                R.layout.fragment_screen_slide_glsl, container);

        Renderer renderer = new BasicRenderer(getContext());
        SurfaceView view = rootView.findViewById(R.id.glsl_content);
        view.setSurfaceRenderer(renderer);

        return rootView;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }

    class BasicRenderer extends Renderer {
        Texture texture = new Texture("quad" + System.nanoTime(), R.drawable.quad);

        BasicRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                DirectionalLight key = new DirectionalLight(-3, 4, 5);
                getCurrentScene().setBackgroundColor(Color.BLUE);
                key.setPower(5.0f);
                getCurrentScene().addLight(key);

                Material material = new Material();
                material.addTexture(texture);
                material.setColorInfluence(0);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.setAmbientColor(Color.LTGRAY);
                material.enableLighting(true);

                Object3D obj = new Cube(2);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                getCurrentCamera().setPosition(3, 4, 5);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getClass().getSimpleName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
}
```

**Comment by LyCharlie** [comment]
try to add following code and switch page quickly
```
    public void pause() {
            view.onPause();
    }
    public void resume() {
            view.onResume();
    }
```

**Comment by contriteobserver** [comment]
Sorry, I am failing to understand how the added methods `pause()` and `resume()` are invoked.

**Comment by truongnv410** [comment]
same error, any update for this problem, thanks
