### ISSUE TITLE
Error `IllegalStateException` in the class `TextureManager.java`

### ISSUE THREAD

**Issue by SandroMachado** [Rajawali/Rajawali#1825]
#### Rajawali Version or Branch
1.1.777

#### Device and Android Version
Samsung, Acer, LG

#### Summary
Sometimes my app produces an `IllegalStateException` error.

#### Steps to Reproduce
Unfortunately I don't have **repro steps**. It looks like a random thing. Any hints on what is causing this?

#### Trace or Log Output
```
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer._setVideoSurface(MediaPlayer.java)
       at android.media.MediaPlayer.setSurface(MediaPlayer.java:758)
       at org.rajawali3d.materials.textures.StreamingTexture.add(StreamingTexture.java:83)
       at org.rajawali3d.materials.textures.TextureManager.taskAdd(TextureManager.java:112)
       at org.rajawali3d.materials.textures.TextureManager.taskReload(TextureManager.java:211)
       at org.rajawali3d.renderer.Renderer.initScene(Renderer.java:366)
       at com.sandro.aerial.RendererActivity.onRenderSurfaceSizeChanged(RendererActivity.java:299)
       at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1519)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by contriteobserver** [comment]
This is a MediaPlayer state issue, we will need to know more about how you are how are you instantiating running MediaPlayer.

**Comment by SandroMachado** [comment]
I am following the same approach of the demo code at the examples folder.

**Comment by contriteobserver** [comment]
does your Renderer class look like this?
```
    public class VideoTextureRenderer extends Renderer {
        private MediaPlayer mMediaPlayer;
        private StreamingTexture mVideoTexture;

        public VideoTextureRenderer(Context context) {
            super(context);
            setFrameRate(24);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.GRAY);

            mMediaPlayer = MediaPlayer.create(getContext(),
                    R.raw.sintel_trailer_480p);
            mMediaPlayer.setLooping(true);

            mVideoTexture = new StreamingTexture("sintelTrailer", mMediaPlayer);
            Material material = new Material();
            material.setColorInfluence(0);
            try {
                material.addTexture(mVideoTexture);
            } catch (Exception e) {
                e.printStackTrace();
            }

            Plane screen = new Plane(3, 2, 2, 2, Vector3.Axis.Y);
            screen.setMaterial(material);
            screen.setX(.1f);
            screen.setY(-.2f);
            screen.setZ(1.5f);
            getCurrentScene().addChild(screen);

            getCurrentCamera().setUpAxis(Vector3.Axis.Z);
            getCurrentCamera().setPosition(1,2,1);
            getCurrentCamera().enableLookAt();
            getCurrentCamera().setLookAt(screen.getPosition());

            mMediaPlayer.start();
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }

        @Override
        protected void onRender(long ellapsedRealtime, double deltaTime) {
            super.onRender(ellapsedRealtime, deltaTime);
            mVideoTexture.update();
        }

        @Override
        public void onPause() {
            super.onPause();
            if (mMediaPlayer != null)
                mMediaPlayer.pause();
        }

        @Override
        public void onResume() {
            super.onResume();
            if (mMediaPlayer != null)
                mMediaPlayer.start();
        }

        @Override
        public void onRenderSurfaceDestroyed(SurfaceTexture surfaceTexture) {
            super.onRenderSurfaceDestroyed(surfaceTexture);
            mMediaPlayer.stop();
            mMediaPlayer.release();
        }

    }
```

**Comment by SandroMachado** [comment]
Yes, I have some minor changes for my use case. I am also playing videos in a live wallpaper.

**Comment by contriteobserver** [comment]
Would you please add that this issue is "when playing videos in a live wallpaper" to the summary?

I am not strong with the live wallpaper infrastructure, and it would be best to alert others that are more knowledgeable with live wallpaper that this might be a factor.

**Comment by SandroMachado** [comment]
I think I found the issue, I didn't did `reset` in the `MediaPlayer` to play a new video in a special use case. 

I will close the issue for now.
