### ISSUE TITLE
Error `ArrayIndexOutOfBoundsException` in the class `TextureManager.java`

### ISSUE THREAD

**Issue by SandroMachado** [Rajawali/Rajawali#1826]
#### Rajawali Version or Branch
1.1.777

#### Device and Android Version
Samsung, HUAWEI and LG

#### Summary
Sometimes my app produces an `ArrayIndexOutOfBoundsException` error.

#### Steps to Reproduce
Unfortunately I don't have **repro steps**. It looks like a random thing. Any hints on what is causing this?

#### Trace or Log Output
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
       at java.util.Collections$SynchronizedList.get(Collections.java:541)
       at org.rajawali3d.materials.textures.TextureManager.taskReload(TextureManager.java:205)
       at org.rajawali3d.renderer.Renderer.initScene(Renderer.java:366)
       at com.sandro.aerial.RendererActivity.onRenderSurfaceSizeChanged(RendererActivity.java:299)
       at org.rajawali3d.view.SurfaceView$RendererDelegate.onSurfaceChanged(SurfaceView.java:232)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1631)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1352)
```

**Comment by jwoolston** [comment]
This was resolved a while back by one of the recent PRs.
