### ISSUE TITLE
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT

### ISSUE THREAD

**Issue by jshwdmnn** [Rajawali/Rajawali#1872]
Hey there,
I've got a pretty big application and a rare but annoying error I can't get behind and can't reproduce properly. It seems to just randomly happen, but rarely. It drives me crazy. That's why I can't provide any particular code snippet or describe it any better but post the error message and maybe you can roughly describe when and how this can happen:

```
E/Rajawali: Could not create framebuffer 2: [1282]: invalid operation
E/Rajawali: Execution Failed: Could not create framebuffer 2: [1282]: invalid operation
E/Rajawali: Could not create framebuffer 2: [1282]: invalid operation
E/Rajawali: Execution Failed: Could not create framebuffer 2: [1282]: invalid operation
D/ufoEGL: Surface destroy: ANDROID_NATIVE_WINDOW_MAGIC
                                                        
                                                        --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: GLThread 363
                                                                Process: com.vypii.android, PID: 356
                                                                java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: returned if the framebuffer does not have at least one image attached to it.
                                                                    at org.rajawali3d.renderer.RenderTarget.bind(RenderTarget.java:311)
                                                                    at org.rajawali3d.scene.Scene.render(Scene.java:1042)
                                                                    at org.rajawali3d.scene.Scene.render(Scene.java:1002)
                                                                    at org.rajawali3d.renderer.Renderer.render(Renderer.java:426)
                                                                    at org.rajawali3d.renderer.SideBySideRenderer.onRender(SideBySideRenderer.java:237)
                                                                    at HomeRenderer3D.onRender(HomeRenderer3D.java:86)
                                                                    at org.rajawali3d.renderer.Renderer.onRenderFrame(Renderer.java:391)
                                                                    at org.rajawali3d.view.SurfaceView$RendererDelegate.onDrawFrame(SurfaceView.java:237)
                                                                    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
                                                                    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777@aar

**Comment by jshwdmnn** [comment]
Guess: It seems to happen when I return from any other activity back to my rajawali SurfaceView!

**Comment by ln206** [comment]
Have you figured out how to solve this problem? It happens sometimes for me too

**Comment by shaji-Dev** [comment]
Anyone figured out a solution for this issue yet?

**Comment by Ram8948** [comment]
any solution I have also same problem?

**Comment by contriteobserver** [comment]
Pretty sure this is an improper UI/Render threading issue, #2195 looks that way, there have been some murmurs about this but @Ram8948 is the first one to give us an example to test this hypothesis.
