### ISSUE TITLE
Render children as batch not working with obj files

### ISSUE THREAD

**Issue by oboforty** [Rajawali/Rajawali#1880]
Hey there,
I'm trying to make batch rendering working. I tried to clone a base cube multiple times (with different positions) and then speed up the rendering by adding these models as children to a parent Cube object and calling _setRenderChildrenAsBatch(true)_ on the parent (in practice i would want to add hundred thousands of the same .obj mesh to a parent this way).

```
        Cube root = new Cube(1);
        root.setMaterial(createMaterial(Color.CYAN));

        Cube base_object = new Cube(1);
        for(int i=0; i<=30;i++) {
            Object3D child = base_object.clone();
            child.setMaterial(createMaterial(Color.rgb(255, i*5, 255)));
            root.addChild(child);
        }

        root.setRenderChildrenAsBatch(true);
        renderer.getCurrentScene().addChild(root);


```

However I get the following error:
```
E/AndroidRuntime: FATAL EXCEPTION: GLThread 211
                  Process: com.vsg.mwgraphics, PID: 6308
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void org.rajawali3d.materials.shaders.VertexShader.setColor(float[])' on a null object reference
                      at org.rajawali3d.materials.Material.applyParams(Material.java:826)
                      at org.rajawali3d.Object3D.render(Object3D.java:295)
                      at org.rajawali3d.Object3D.render(Object3D.java:343)
                      at org.rajawali3d.Object3D.render(Object3D.java:184)
                      at org.rajawali3d.scene.Scene.render(Scene.java:1135)
                      at org.rajawali3d.scene.Scene.render(Scene.java:1002)
                      at org.rajawali3d.renderer.Renderer.render(Renderer.java:426)
                      at org.rajawali3d.renderer.Renderer.onRender(Renderer.java:416)
                      at com.vsg.mwgraphics.MapRenderer.onRender(MapRenderer.java:65)
                      at org.rajawali3d.renderer.Renderer.onRenderFrame(Renderer.java:391)
                      at org.rajawali3d.view.SurfaceView$RendererDelegate.onDrawFrame(SurfaceView.java:237)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
```

For some reason when i'm applying batch rendering, the shaders seem to be gone for materials. Without _setRenderChildrenAsBatch_ the code works perfectly.

**Comment by contriteobserver** [comment]
This code works for me, I must be misunderstanding your issue, please clarify:
```
    private class BatchRenderer extends Renderer {

        public BatchRenderer(Context context) {
            super(context);
        }

        private Material createMaterial(int color){
            Material material = new Material();
            material.setColor(color);
            return material;
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.RED);

                Cube root = new Cube(1);
                root.setMaterial(createMaterial(Color.CYAN));

                Cube base_object = new Cube(1);
                for(int i=0; i<=30;i++) {
                    Object3D child = base_object.clone();
                    child.setMaterial(createMaterial(Color.rgb(255, i*5, 255)));
                    root.addChild(child);
                }

                root.setRenderChildrenAsBatch(true);
                renderer.getCurrentScene().addChild(root);

            } catch (Exception e) {
                Log.d(getLocalClassName(), e.toString());
            }

        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
```

**Comment by jwoolston** [comment]
Closing issue as stale/resolved. Please inform if issues persist.
