### ISSUE TITLE
GLES20.GL_EXTENSIONS NullPointerException

### ISSUE THREAD

**Issue by changjiashuai** [Rajawali/Rajawali#1912]
#### Rajawali Version or Branch
v1.1.777

#### Device and Android Version
android 7.0

#### Summary
 String extensions = GLES20.glGetString(GLES20.GL_EXTENSIONS);
 mExtensions = extensions.split(" ");
NullPointerException()

#### Steps to Reproduce
 val mSurfaceView: SurfaceView = findViewById(R.id.surfaceView) as SurfaceView
 mSurfaceView.setSurfaceRenderer(PanoRenderer(this))

#### Trace or Log Output
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
                                                     at org.rajawali3d.util.Capabilities.initialize(Capabilities.java:162)
                                                     at org.rajawali3d.util.Capabilities.<init>(Capabilities.java:67)
                                                     at org.rajawali3d.util.Capabilities.getInstance(Capabilities.java:73)
                                                     at org.rajawali3d.materials.Material.<init>(Material.java:283)
                                                     at org.rajawali3d.materials.Material.<init>(Material.java:270)
                                                     at org.rajawali3d.postprocessing.passes.CopyPass.<init>(CopyPass.java:26)
                                                     at org.rajawali3d.postprocessing.PostProcessingManager.<init>(PostProcessingManager.java:95)
                                                     at org.rajawali3d.postprocessing.PostProcessingManager.<init>(PostProcessingManager.java:59)
                                                     at com.arashivision.insta360vr.renderer.PanoRenderer.<init>(PanoRenderer.kt:27)
                                                     at com.arashivision.insta360vr.TestActivity.onCreate(TestActivity.kt:17)
                                                     at android.app.Activity.performCreate(Activity.java:6320)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2526)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2633) 
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:169) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:171) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)

**Comment by jwoolston** [comment]
What device is this on

**Comment by contriteobserver** [comment]
This may be a case of creating a `Material` before the surface has settled.

If one can isolate the `Material` in question, create it with `new Material(true)` this defers the capabilities check until after the surface is setup.

**Comment by changjiashuai** [comment]
@jwoolston HUAWEI CAZ-TL10 and Nubia NX569H

**Comment by changjiashuai** [comment]
@contriteobserver init ```
        mPostProcessingManager = PostProcessingManager(this)``` in constructor fun is there a problem?

**Comment by contriteobserver** [comment]
Yes, that would be a problem, `PostProcessingManager` creates a `CopyPass` in it's constructor, and `CopyPass` a type of material that requires the EGL context to be available before it can be constructed.

Best to construct `PostProcessingManager` in `initScene`.

**Comment by changjiashuai** [comment]
I got it. thank you. @contriteobserver

**Comment by jwoolston** [comment]
Closing this issue as resolved. Please let us know if issues persist.
