### ISSUE TITLE
Crash happened at org.rajawali3d.view.SurfaceView.onResume(SurfaceView.java:108)

### ISSUE THREAD

**Issue by FelixZ88** [Rajawali/Rajawali#1937]
#### 
java.lang.NullPointerException: 
  at android.opengl.GLSurfaceView.onResume(GLSurfaceView.java:585)
  at org.rajawali3d.view.SurfaceView.onResume(SurfaceView.java:108)
  at org.rajawali3d.view.SurfaceView.onAttachedToWindow(SurfaceView.java:130)
  at android.view.View.dispatchAttachedToWindow(View.java:15542)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1648)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6763)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
  at android.view.Choreographer.doCallbacks(Choreographer.java:735)
  at android.view.Choreographer.doFrame(Choreographer.java:667)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
  at android.os.Handler.handleCallback(Handler.java:761)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:156)
  at android.app.ActivityThread.main(ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, here is my code, what is wrong with it?
```
public class BombshellActivity extends AppCompatActivity {
    SurfaceView surface;
    Renderer renderer;
    Object3D obj;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bombshell);

        renderer = new BasicRenderer(getApplicationContext());
        surface = (SurfaceView) findViewById(R.id.glsl_content);
        surface.setSurfaceRenderer(renderer);
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d(getLocalClassName(), "onResume");
    }

    class BasicRenderer extends Renderer {

        public BasicRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            getCurrentScene().setBackgroundColor(Color.BLUE);

            DirectionalLight key = new DirectionalLight(-3,-4,-5);
            key.setPower(2);
            getCurrentScene().addLight(key);

            Material material = new Material();
            material.setColor(Color.GREEN);
            material.setDiffuseMethod(new DiffuseMethod.Lambert());
            material.enableLighting(true);

            obj = new Sphere(1, 24, 24);
            obj.setMaterial(material);
            getCurrentScene().addChild(obj);

            getCurrentCamera().setPosition(3,3,3);
            getCurrentCamera().setLookAt(obj.getPosition());
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {
        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
}
```
Logs show `onResume` is called:
```
06-28 22:19:04.389 14194-14194/com.example.bombshellspike D/BombshellActivity: onResume
```

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.

**Comment by TailyDuan** [comment]
I meet the problem, Have you solved it ?
