### ISSUE TITLE
Problem with destroy on 1.0.325

### ISSUE THREAD

**Issue by AnthonyMarc** [Rajawali/Rajawali#1942]
Hi! I'm developing a game using rajawali. I'm using version **1.0.325** because the newer version of rajawali don't display the models in my device (**Samsung S5 mini with Marshmellow 6.0**). I have a trouble regarding the use of destroy in an AWD model with some childs. I have the necessity of using the same model more time, so i'm cloning it in this way:
**newTree=tree.clone(true,true);**

This variable will be stored in a LinkedList of Object3D (TreesOnScreenList).
The problem came when I want to remove the object from scene and destroy the object. Calling:
**TreesOnScreenList.getFirst.destroy();**

I go into this error:

**07-07 13:39:42.684 14782-15204/it.am.flyhighbird D/libEGL: eglTerminate EGLDisplay = 0x5844b4bc
07-07 13:39:42.684 14782-15204/it.am.flyhighbird E/AndroidRuntime: FATAL EXCEPTION: GLThread 9195
Process: it.am.flyhighbird, PID: 14782
 java.lang.NullPointerException: Attempt to invoke virtual method 'void org.rajawali3d.Geometry3D.validateBuffers()' on a null object reference
at org.rajawali3d.Object3D.preRender(Object3D.java:167)
at org.rajawali3d.Object3D.render(Object3D.java:200)
at org.rajawali3d.Object3D.render(Object3D.java:181)
at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:1109)
at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:971)
at org.rajawali3d.renderer.RajawaliRenderer.render(RajawaliRenderer.java:422)
at org.rajawali3d.renderer.RajawaliRenderer.onRender(RajawaliRenderer.java:412)
at it.am.flyhighbird.GameRenderer.onRender(GameRenderer.java:328)
at org.rajawali3d.renderer.RajawaliRenderer.onRenderFrame(RajawaliRenderer.java:387)
at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onDrawFrame(RajawaliSurfaceView.java:228)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)**

Do you know why this error came out? Tried many solution, but nothing worked for now.

**Comment by rpicolet** [comment]
Removing an Object3D from a Scene is not immediate, but queued as a task for the GL thread. It is possible the destroy actually completes before the remove gets a chance to run but after a frame render has started using the now destroyed (but not yet removed) Object3D.  If this is indeed the cause of the problem, you could consider performing both operations together on the GL thread in a FrameCallback or perhaps using GLSurfaceView.queueEvent()...

**Comment by AnthonyMarc** [comment]
Effectively I'm using external classes for every type of object I'm using. I tried your proposals but without success. I need to destroy an object after an animation. This is what i've done:

private class endAnim implements IAnimationListener
{
        Object3D tree;
        endAnim(Object3D Tree)
        {
            tree=Tree;
        }

        @Override
        public void onAnimationEnd(Animation animation)
        {
            //currentScene.unregisterAnimation(treesOnScreenAnimationList.getFirst());

            queueEvent(new Runnable()
            {
                // This method will be called on the rendering thread:
                public void run()
                {
                    getCurrentScene().removeChild(tree);
                    tree.destroy();
                }
            });
            treesOnScreenList.removeFirst();
            treesTypeOnScreenList.removeFirst();
            treesOnScreenAnimationList.removeFirst();
        }
        @Override
        public void onAnimationRepeat(Animation animation) {}
        @Override
        public void onAnimationStart(Animation animation) {}
        @Override
        public void onAnimationUpdate(Animation animation, double interpolatedTime) {}
}

These are the errors; the row 211 points at "queueEvent(new Runnable()":

07-08 10:08:08.827 7746-8184/it.am.flyhighbird D/libEGL: eglTerminate EGLDisplay = 0x584844bc
07-08 10:08:08.827 7746-8184/it.am.flyhighbird E/AndroidRuntime: FATAL EXCEPTION: GLThread 2887
Process: it.am.flyhighbird, PID: 7746
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.queueEvent(java.lang.Runnable)' on a null object reference
at android.opengl.GLSurfaceView.queueEvent(GLSurfaceView.java:677)
at it.am.flyhighbird.elements.TreeManagement$endAnim.onAnimationEnd(TreeManagement.java:211)
at org.rajawali3d.animation.Animation.eventEnd(Animation.java:334)
at org.rajawali3d.animation.Animation.update(Animation.java:250)
at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:1044)
at org.rajawali3d.scene.RajawaliScene.render(RajawaliScene.java:971)
at org.rajawali3d.renderer.RajawaliRenderer.render(RajawaliRenderer.java:422)
at org.rajawali3d.renderer.RajawaliRenderer.onRender(RajawaliRenderer.java:412)
at it.am.flyhighbird.GameRenderer.onRender(GameRenderer.java:332)
at org.rajawali3d.renderer.RajawaliRenderer.onRenderFrame(RajawaliRenderer.java:387)
at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onDrawFrame(RajawaliSurfaceView.java:228)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)

**Comment by rpicolet** [comment]
The stack trace clearly indicates that the problem is with the GLSurfaceView$GLThread.queueEvent call on a null GLThread instance, which makes no sense since the whole trace is on the obviously-running GL thread.  But I cannot see how the code you provided could even compile (much less run to produce the given stack trace), as it calls queueEvent without a GLSurfaceView instance qualifier.

**Comment by jwoolston** [comment]
Closing as resolved/stale. Please inform if issues persist.
