### ISSUE TITLE
Error "Could not create framebuffer" after resize surface view

### ISSUE THREAD

**Issue by paoloach** [Rajawali/Rajawali#2019]
#### Rajawali Version or Branch
org.rajawali3d:rajawali:1.1.777

#### Device and Android Version
Xiaomi redmi 3, android version 5.1.1

#### Summary
E/Rajawali: Could not create framebuffer: [1281]: invalid value
This message arise when I try to change the  surface dimension after the application is running.
I overloaded the function onLayoutChange so that when this event appens,  my application performs the fellowing steps:
        renderer.onSurfaceViewLayoutChange(left, top, right, bottom)
        renderer.onResume()
I see that this function is called, rightly, when the application start and when I iask to it to change the layout.
But in this later case, onSurfaceViewLayoutChange throw an exception.
This it appens only in my real device. Using an emulato with the same android version, the problem doesn't happen

Seeing the library code, I see that the problem arise when it is called glGenFramebuffers/glBindFramebuffer 
If I well understood, these pair of functions create a new framebuffer and it bind it, but it seems to me that the previous one, that created when the application starts, it's not released or unbind (I don't see any
 call to RenderTarget::unbind() or RenderTarget::remove() )
It can be that my device support only one binding to frame buffer ? 

#### Steps to Reproduce
On xiomi redmi 3
Using a layout where there is a SurfaceView and another view with visibility=gone
After the application is started and showed, change the visibility=visibile in order to change the layout  of the surface view
 
#### Trace or Log Output
glBindBuffer(0x8893, 0);
 glBindBuffer(0x8892, 0);
D/libEGL: glBindFramebuffer(0x8d40, 0);
 glGenFramebuffers(1, (GLuint *) 0x1313efbc);
D/libEGL: glBindFramebuffer(0x8d40, 2);
 D/libEGL: glGetError();
 E/Rajawali: Could not create framebuffer: [1281]: invalid value
 E/AndroidRuntime: FATAL EXCEPTION: GLThread 18516
                                                                                      Process: it.achdjian.paolo.temperaturemonitor, PID: 14104
                                                                                      java.lang.RuntimeException: Could not create framebuffer: [1281]: invalid value   at org.rajawali3d.renderer.RenderTarget.checkGLError(RenderTarget.java:333)   at org.rajawali3d.renderer.RenderTarget.create(RenderTarget.java:253) at org.rajawali3d.renderer.RenderTarget.reload(RenderTarget.java:324) at

**Comment by contriteobserver** [comment]
having trouble reproducing this issue, what is wrong with this code:
```
public class ResizeActivity extends AppCompatActivity {
    Renderer renderer;
    SurfaceView surfaceView;
    TextView textView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_resize);

        renderer = new BasicRenderer(getApplicationContext());

        surfaceView = findViewById(R.id.glsl_content);
        surfaceView.setSurfaceRenderer(renderer);
        surfaceView.setOnTouchListener(new OnTouchListener());

        textView = findViewById(R.id.text_content);
        textView.setOnTouchListener(new OnTouchListener());
    }

    class OnTouchListener implements View.OnTouchListener {
        @Override
        public boolean onTouch(View view, MotionEvent motionEvent) {
            switch(textView.getVisibility()) {
                case View.GONE:
                    textView.setVisibility(View.VISIBLE);
                    break;
                default:
                    textView.setVisibility(View.GONE);
                    break;
            }
            return false;
        }
    }

    class BasicRenderer extends Renderer {
        public BasicRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                getCurrentScene().setBackgroundColor(Color.BLUE);
                Material material = new Material();
                material.setColor(Color.CYAN);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.enableLighting(true);
                Cube cube = new Cube(1);
                cube.setMaterial(material);
                getCurrentScene().addChild(cube);

                ALight key = new DirectionalLight();
                key.setPosition(3,-4,5);
                key.setPower(2);
                getCurrentScene().addLight(key);
                key.setLookAt(cube.getPosition());

                getCurrentCamera().setPosition(3,3,3);
                getCurrentCamera().setLookAt(cube.getPosition());

            } catch (Exception e) {
                Log.d(getClass().getSimpleName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {

        }
    }
}
```
and the layout file:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.rajawali.resizespike.ResizeActivity">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <org.rajawali3d.view.SurfaceView
            android:id="@+id/glsl_content"
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            />

        <TextView
            android:id="@+id/text_content"
            android:visibility="gone"
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:textSize="32pt"
            android:textColor="@color/colorPrimary"
            android:text="Hello World!"
            />
    </LinearLayout>
</android.support.constraint.ConstraintLayout>
```

**Comment by paoloach** [comment]
Actually, your simple application works fine also on my device.
I think to have too trivialized the problem, so I will try to simplify my application in order to reproduce the problem. 

Anyway, I created a patch that resolve for me the issue
[RenderTarget.patch.zip](https://github.com/Rajawali/Rajawali/files/1485885/RenderTarget.patch.zip)
but I don'k know opengl so I don't know if it is right or introduce some other problem.
