### ISSUE TITLE
How to use Serialize obj using the master rajawali? 

### ISSUE THREAD

**Issue by pren1** [Rajawali/Rajawali#2022]
#### Rajawali Version or Branch
rajawali 1.0.186

#### Device and Android Version
Google Pixel, compileSdkVersion 26

#### Summary
Hello, it seems that people cannot Serialize obj when they use master rajawali. But if an obj is too large, how can we load it quickly? How do people solve this problem when they use master rajawali? Thanks in advance.

By the way, I got these codes from the internet, but they are for v0.9 and didn't work in my case (I use the master rajawali):
`MeshExporter exporter = new MeshExporter(myObject);
            exporter.export("myfile.ser", ExportType.SERIALIZED, true);`

**Comment by nathanb94** [comment]
I have the same problem, 
i try with compile version ; 
'org.rajawali3d:rajawali:1.0.186-SNAPSHOT@aar'
and 
'org.rajawali3d:rajawali:1.1.970'

but i haven't any access to "ExportType"

I try to change "ExportType" to 

exporter.export("myBaseObject3Dname", new AExporter() {
            @Override
            public void export() {

            }
        }.getClass()); 

but it's not work.

I get the bug:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.nathanb.rajawalynew, PID: 5811
org.rajawali3d.util.MeshExporter$ExporterException: java.lang.NoSuchMethodException: <init> []
at org.rajawali3d.util.MeshExporter.export(MeshExporter.java:103)
at org.rajawali3d.util.MeshExporter.export(MeshExporter.java:60)
