### ISSUE TITLE
NullPointerException in SlerpAnimation3D

### ISSUE THREAD

**Issue by andrey-blak** [Rajawali/Rajawali#2032]
#### Rajawali Version or Branch
v1.1.970

#### Summary
The `mTmpQuatVector` variable is used in `quaternionFromVector` method before the initialisation. 

#### Steps to Reproduce
Code to reproduce the exception:
```
                Animation3D animation = new SlerpAnimation3D(new Vector3(), new Vector3());
                animation.setTransformable3D(monkey);
                animation.setDurationMilliseconds(3000);
                getCurrentScene().registerAnimation(animation);
                animation.play();
```

#### Trace or Log Output
```
W: java.lang.NullPointerException: Attempt to invoke virtual method 'org.rajawali3d.math.vector.Vector3 org.rajawali3d.math.vector.Vector3.crossAndSet(org.rajawali3d.math.vector.Vector3, org.rajawali3d.math.vector.Vector3)' on a null object reference
W:     at org.rajawali3d.animation.SlerpAnimation3D.quaternionFromVector(SlerpAnimation3D.java:73)
W:     at org.rajawali3d.animation.SlerpAnimation3D.<init>(SlerpAnimation3D.java:50)
```

**Comment by contriteobserver** [comment]
good catch, thanks...

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
