### ISSUE TITLE
penGL Error: null 1286

### ISSUE THREAD

**Issue by GauravCreed** [Rajawali/Rajawali#2046]
`FATAL EXCEPTION: GLThread 256
                                                                             Process: christmas.live.wallpaper.free, PID: 4433
                                                                             java.lang.RuntimeException: OpenGL Error: null 1286
                                                                                 at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:513)
                                                                                 at christmas.live.wallpaper.free.Renderer.onDrawFrame(Renderer.java:232)
                                                                                 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                                                 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

Getting this error on tablet and also can not able to load any video on tablet, but it working fine in my phone device

is there ay solution for this then please help me.

thanks(_)

**Comment by contriteobserver** [comment]
To get started, we need to know the Rajawali version. 

However, since there is a reference to `rajawali.renderer.RajawaliRenderer`, we at least know the version is an old (AnchorStream) `1.0.XXX`. There is a good probability that upgrading to our current (Bombshell) `1.1.970` version will resolve this issue.

**Comment by ToxicBakery** [comment]
This issue appears to be resolved, please reopen if that is not the case.
