### ISSUE TITLE
AWD files cannot be loaded

### ISSUE THREAD

**Issue by ZhangGuangXin** [Rajawali/Rajawali#2073]
I imported a DAE file into away builder and saved it as AWD file. I used rajawali to load this AWD file through the LoaderAWD class with an error.

The code was:
LoaderAWD parser = new LoaderAWD(mContext.getResources(), mTextureManager, R.raw.awd_test);
parser.parse();

In the second line of code, the following error occurs:
org.rajawali3d.loader.ParsingException: Unexpected error. File is not in a supported AWD format.

**Comment by ZhangGuangXin** [comment]
Excuse me, has anyone ever had such a problem?  Is there something wrong with my AWD file?

**Comment by ZhangGuangXin** [comment]
I select "UNCOMPRESSED", click "file" -- > "save as", and get an AWD file, but errors still occur in the program:

org.rajawali3d.examples W/System.err: org.rajawali3d.loader.ParsingException: Block did not end in the correct location. Expected : 209 Ended : 206
        at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:298)
        at org.rajawali3d.examples.examples.animation.SkeletalAnimationAWDFragment$SkeletalAnimationAWDRenderer.initScene(SkeletalAnimationAWDFragment.java:45)
        at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:352)
12-17 21:42:50.264 16097-16662/org.rajawali3d.examples W/System.err:     at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1264)
        at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:995)
    org.rajawali3d.loader.ParsingException: Unexpected error. File is not in a supported AWD format.
        at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:311)
        at org.rajawali3d.examples.examples.animation.SkeletalAnimationAWDFragment$SkeletalAnimationAWDRenderer.initScene(SkeletalAnimationAWDFragment.java:45)
        at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:352)
        at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1264)
        at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:995)
    Caused by: org.rajawali3d.loader.ParsingException: Block did not end in the correct location. Expected : 209 Ended : 206
        at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:298)
    	... 4 more
    org.rajawali3d.loader.ParsingException: Unexpected error. File is not in a supported AWD format.
        at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:311)
        at org.rajawali3d.examples.examples.animation.SkeletalAnimationAWDFragment$SkeletalAnimationAWDRenderer.initScene(SkeletalAnimationAWDFragment.java:45)
        at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:352)
        at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1264)
12-17 21:42:50.265 16097-16662/org.rajawali3d.examples W/System.err:     at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:995)
    Caused by: org.rajawali3d.loader.ParsingException: Block did not end in the correct location. Expected : 209 Ended : 206
        at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:298)

**Comment by ZhangGuangXin** [comment]
Is it because I exported AWD files the wrong way in the away builder?

**Comment by ToxicBakery** [comment]
>Caused by: org.rajawali3d.loader.ParsingException: Block did not end in the correct location. Expected : 209 Ended : 206

That's an interesting issue. Initially, I would expect something changed in AwayBuilder but they have not pushed any changes in years so I'm not sure. I wrote the AWD base parser and the exception being thrown is a sanity check to ensure block parsers are started at the right offsets. 

You can debug this issue though by comparing the parser to your generated AWD file and the specification.

https://github.com/awaytools/awd-sdk/blob/master/docs/AWD_format_specification2_1_Alpha.pdf

All of the block parsers are written to that specification (as close as we can).

**Comment by ZhangGuangXin** [comment]
I changed a DAE file and exported it as AWD file with away builder. There was nothing wrong with the parsing this time, but there was something else wrong:
final LoaderAWD parser = new LoaderAWD(mContext.getResources(), mTextureManager, R.raw.test_awd);
				parser.parse();
				SkeletalAnimationObject3D mObject = (SkeletalAnimationObject3D) parser.getParsedObject(); //This is a mistake

The error output is:
12-25 15:45:01.603 32274-32513/org.rajawali3d.examples W/System.err: java.lang.ClassCastException: org.rajawali3d.Object3D cannot be cast to org.rajawali3d.animation.mesh.SkeletalAnimationObject3D
12-25 15:45:01.605 32274-32513/org.rajawali3d.examples W/System.err:     at org.rajawali3d.examples.examples.animation.SkeletalAnimationAWDFragment$SkeletalAnimationAWDRenderer.initScene(SkeletalAnimationAWDFragment.java:54)
12-25 15:45:01.608 32274-32513/org.rajawali3d.examples W/System.err:     at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:352)
12-25 15:45:01.610 32274-32513/org.rajawali3d.examples W/System.err:     at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1264)
12-25 15:45:01.612 32274-32513/org.rajawali3d.examples W/System.err:     at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:995)

**Comment by ZhangGuangXin** [comment]
What's the reason?
