### ISSUE TITLE
Binary XML file line #10: Error inflating class org.rajawali3d.view.TextureView

### ISSUE THREAD

**Issue by vuthaiduy1990** [Rajawali/Rajawali#2118]
#### Rajawali Version or Branch
Newest version

#### Device and Android Version
Compile SDK Version: API 27
Build Tools Version: 28.0.3

#### Summary
I fork then build Rajawali library into .aar file to attach to my project
In activity.xml, I add TextureView like below
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:textureview="http://schemas.android.com/apk/res-auto"
    android:id="@+id/playGround"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <org.rajawali3d.view.TextureView
        android:id="@+id/world"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        textureview:frameRate="60.0"
        textureview:renderMode="RENDER_WHEN_DIRTY">
    </org.rajawali3d.view.TextureView>
</FrameLayout>`

But when launching app I get the following error. Thanks for any help.

#### Trace or Log Output
`Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class org.rajawali3d.view.TextureView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at the.miner.education.activity.GM3DMakerSpaceActivity.onCreate(GM3DMakerSpaceActivity.java:165)`

**Comment by contriteobserver** [comment]
Having trouble reproducing this issue, what is wrong with this code:
```
public class MainActivity extends AppCompatActivity {
    Renderer renderer;
    ISurface view;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        view = findViewById(R.id.glsl_content);
        renderer = new BasicRenderer(this);

        view.setSurfaceRenderer(renderer);
    }

    class BasicRenderer extends Renderer {

        public BasicRenderer(Context context) {
            super(context);
        }

        @Override
        protected void initScene() {
            try {
                DirectionalLight key = new DirectionalLight(-3,4,5);
                getCurrentScene().setBackgroundColor(Color.BLUE);
                key.setPower(5.0f);
                getCurrentScene().addLight(key);

                Material material = new Material();
                material.setColor(Color.GREEN);
                material.setDiffuseMethod(new DiffuseMethod.Lambert());
                material.setAmbientColor(Color.LTGRAY);
                material.enableLighting(true);

                Object3D obj = new Cube(2);
                obj.setMaterial(material);
                getCurrentScene().addChild(obj);

                Animation3D anim = new RotateOnAxisAnimation(Vector3.Axis.X, 360);
                anim.setTransformable3D(obj);
                anim.setDurationMilliseconds(4321);
                anim.setRepeatMode(Animation.RepeatMode.INFINITE);
                anim.play();
                getCurrentScene().registerAnimation(anim);

                getCurrentCamera().setPosition(3,4,5);
                getCurrentCamera().setLookAt(obj.getPosition());
            } catch (Exception e) {
                Log.d(getLocalClassName(), e.getMessage());
            }
        }

        @Override
        public void onOffsetsChanged(float xOffset, float yOffset, float xOffsetStep, float yOffsetStep, int xPixelOffset, int yPixelOffset) {

        }

        @Override
        public void onTouchEvent(MotionEvent event) {
        }
    }
}
```
and Layout
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:textureview="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <org.rajawali3d.view.TextureView
        android:id="@+id/glsl_content"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        
        textureview:frameRate="60.0"
        textureview:renderMode="RENDER_WHEN_DIRTY"

        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</android.support.constraint.ConstraintLayout>
```

**Comment by vuthaiduy1990** [comment]
> contriteobserver

Did you use my attached rajawali-release.aar. I built from latest code on github.
You can check my code here
[RajawaliTest.zip](https://github.com/Rajawali/Rajawali/files/2899334/RajawaliTest.zip)

**Comment by contriteobserver** [comment]
It appears that this issue is another instance of the recent kotin dependency issues brought up in #2105 

In the interim, a workaround is to add a `kotin-stdlib` dependency to application builds, either using `File >> Project Structure >> app >> Dependencies >> + >> Library Dependency` and search for `kotlin-stdlib`, or add this line to `dependencies` in `app/build.gradle`:
```
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'
```
