### ISSUE TITLE
Caused by: org.rajawali3d.loader.ParsingException: Couldn't find texture ingrid

### ISSUE THREAD

**Issue by ShirleyLuoppx** [Rajawali/Rajawali#2504]
i'm poor in English. pardon me

Here is my error logcat:

```
W/System.err: org.rajawali3d.loader.ParsingException: org.rajawali3d.loader.ParsingException: Couldn't find texture ingrid
W/System.err:     at org.rajawali3d.loader.md5.LoaderMD5Mesh.parse(LoaderMD5Mesh.java:142)
W/System.err:     at com.ppx.dailystudy.opengl.rajawali.SkeletalAnimationFragment$SkeletalAnimationRender.initScene(SkeletalAnimationFragment.java:101)
W/System.err:     at org.rajawali3d.renderer.Renderer.onRenderSurfaceSizeChanged(Renderer.java:351)
W/System.err:     at org.rajawali3d.view.TextureView$GLThread.guardedRun(TextureView.java:1264)
W/System.err:     at org.rajawali3d.view.TextureView$GLThread.run(TextureView.java:995)
W/System.err: Caused by: org.rajawali3d.loader.ParsingException: Couldn't find texture ingrid
W/System.err:     at org.rajawali3d.loader.md5.LoaderMD5Mesh.createObjects(LoaderMD5Mesh.java:450)
W/System.err:     at org.rajawali3d.loader.md5.LoaderMD5Mesh.parse(LoaderMD5Mesh.java:137)
W/System.err: 	... 4 more
```

i import Rajawali by  `   implementation 'org.rajawali3d:rajawali:1.1.970' `     with Android Studio

when i want to code a demo about **SkeletalAnimation** and write a demo like this whic from the demo Rajawali ,but i got a error '**Couldn't find texture ingrid**' ,but i already import all raw file resource into my project  include the .md5mesh and .md5anim, but still had the error , i don't know why , help me guys , and thanks a lot if u could repaly me .

```
 ...

    protected void initScene() {
        //加载灯光
        DirectionalLight light = new DirectionalLight(0, -0.2f, -1.0f);
        light.setColor(1f, 1f, 1f);
        light.setPower(2);
        getCurrentScene().addLight(light);
        getCurrentCamera().setZ(8);

        try {
            Log.d("TAG", "initScene: that's ok ");//this has printed
            //加载mesh模型文件
            LoaderMD5Mesh loaderMD5Mesh = new LoaderMD5Mesh(this, R.raw.ingrid_mesh);
            Log.d("TAG", "initScene: " + loaderMD5Mesh);////this has printed and not null 
            loaderMD5Mesh.parse();/////////////////////////////////////////this line is the error line
            Log.d("TAG", "initScene:2 ");////this don't printe
            object3D = (SkeletalAnimationObject3D) loaderMD5Mesh.getParsedAnimationObject();

            //加载idle的动画模型
            LoaderMD5Anim loaderMD5Anim = new LoaderMD5Anim("idle", this, R.raw.ingrid_idle);
            loaderMD5Anim.parse();
            idleSequence = (SkeletalAnimationSequence) loaderMD5Anim.getParsedAnimationSequence();
            ...

            object3D.setAnimationSequence(idleSequence);
            object3D.setFps(24);
            object3D.setScale(0.8);
            object3D.play();

            getCurrentScene().addChild(object3D);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by ShirleyLuoppx** [comment]
slove it!
i forgot to add the texture png to my drawable folder.
